/* 考点总表：考点组编号 → 考点名 + 对应课节。

   题目本身按篇章拆在 exam-data-1.js ~ exam-data-7.js 里，本文件只留考点表。
   交卷后前端按考点组聚合对错并上报，米羊个人中心据此展示薄弱点和补课入口。
   服务端 auth-service.py 解析本表（和 course-data.js 同款 mtime 热加载），
   改考点名或补课链接只动这里，不用重启服务。

   编号规则：1-22 是早期综合卷的考点（题目已并入第一、二篇章，编号保留给历史成绩兜底）；
   1xx-5xx 对应大模型原理到自我改进五个主线篇章，7xx 对应协作方法论篇（Vibe Coding），6xx 对应 Grok Build 专题。
   6xx / 7xx 的百位与篇章序号对不上，是 2026-08-09 篇章重排留下的：Grok Build 降级为
   选修专题、Vibe Coding 补位原第六篇章（现协作方法论篇），但考点编号已经写进学员的历史成绩和薄弱点记录里，
   重编号会让这些数据全部对不上，所以只改展示文案，不动编号。 */
window.EXAM_TOPICS = {
 "1": {"name": "Token 概率生成机制", "file": "1-2-base.html"},
 "2": {"name": "模型联网能力边界", "file": "7-2.html"},
 "3": {"name": "幻觉的成因", "file": "1-2-hallucination.html"},
 "4": {"name": "RAG 的核心作用", "file": "1-2-mitigation-rag.html"},
 "5": {"name": "RAG 的局限", "file": "1-2-mitigation-rag.html"},
 "6": {"name": "Agent 概念", "file": "7-1.html"},
 "7": {"name": "工具调用机制", "file": "7-2.html"},
 "8": {"name": "Temperature 采样", "file": "1-2-mitigation-temp.html"},
 "9": {"name": "提示词起效原理", "file": "1-2-prompt-power.html"},
 "10": {"name": "对话记忆原理", "file": "5-1.html"},
 "11": {"name": "Prompt 注入攻击", "file": "prompt-attack.html"},
 "12": {"name": "幻觉与创意的关系", "file": "1-2-hallucination.html"},
 "13": {"name": "技术栈底层机制", "file": "1-2-base.html"},
 "14": {"name": "模型能力边界", "file": "ai-tips-boundary.html"},
 "15": {"name": "Agent 核心能力", "file": "7-1.html"},
 "16": {"name": "幻觉缓解手段", "file": "summary-1b.html"},
 "17": {"name": "大模型基本认知", "file": "summary-1.html"},
 "18": {"name": "RAG 工作流程", "file": "1-2-mitigation-rag.html"},
 "19": {"name": "搜索功能的实现", "file": "7-2.html"},
 "20": {"name": "幻觉的内在性", "file": "1-2-hallucination.html"},
 "21": {"name": "RAG 与幻觉边界", "file": "1-2-mitigation-rag.html"},
 "22": {"name": "角色设定原理", "file": "6-1.html"},
 "101": {"name": "SFT 解决的问题", "file": "1-2-sft.html"},
 "102": {"name": "Base 模型行为特征", "file": "1-2-base.html"},
 "103": {"name": "Chat Template 结构", "file": "1-2-sft.html"},
 "104": {"name": "对话即补全本质", "file": "1-2-api.html"},
 "105": {"name": "伪造聊天记录实验", "file": "1-2-fake-chat.html"},
 "106": {"name": "训练与推理的区别", "file": "train-vs-infer.html"},
 "107": {"name": "参数与上下文之别", "file": "1-2-hallucination.html"},
 "108": {"name": "提示词等效训练机制", "file": "1-2-prompt-power.html"},
 "109": {"name": "Temperature 缩放机制", "file": "1-2-mitigation-temp.html"},
 "110": {"name": "场景化采样参数", "file": "1-2-mitigation-temp.html"},
 "111": {"name": "幻觉类型判别", "file": "summary-1.html"},
 "112": {"name": "GPT 预训练跃进", "file": "1-2-gpt.html"},
 "113": {"name": "Token 与分词", "file": "1-2-vocab.html"},
 "114": {"name": "RAG 意图过滤优化", "file": "rag-advanced.html"},
 "115": {"name": "Prompt 约束的边界", "file": "1-2-mitigation-prompt.html"},
 "116": {"name": "评测与审核环节", "file": "1-2-mitigation-eval.html"},
 "117": {"name": "训练数据规模认知", "file": "training-data.html"},
 "118": {"name": "RAG 成本与优化", "file": "rag-advanced.html"},
 "119": {"name": "缓解策略场景匹配", "file": "summary-1b.html"},
 "120": {"name": "参数冻结与对话", "file": "train-vs-infer.html"},
 "121": {"name": "SFT 的能力边界", "file": "1-2-sft.html"},
 "122": {"name": "温度与知识边界", "file": "1-2-mitigation-temp.html"},
 "123": {"name": "幻觉率指标管理", "file": "1-2-mitigation-eval.html"},
 "124": {"name": "RAG 检索风险", "file": "1-2-mitigation-rag.html"},
 "125": {"name": "Token 概率生成机制", "file": "1-2-base.html"},
 "126": {"name": "幻觉的成因", "file": "1-2-hallucination.html"},
 "127": {"name": "RAG 的核心作用", "file": "1-2-mitigation-rag.html"},
 "128": {"name": "RAG 的局限", "file": "1-2-mitigation-rag.html"},
 "129": {"name": "Temperature 采样", "file": "1-2-mitigation-temp.html"},
 "130": {"name": "提示词起效原理", "file": "1-2-prompt-power.html"},
 "131": {"name": "幻觉与创意的关系", "file": "1-2-hallucination.html"},
 "132": {"name": "技术栈底层机制", "file": "1-2-base.html"},
 "133": {"name": "幻觉缓解手段", "file": "summary-1b.html"},
 "134": {"name": "大模型基本认知", "file": "summary-1.html"},
 "135": {"name": "RAG 工作流程", "file": "1-2-mitigation-rag.html"},
 "136": {"name": "幻觉的内在性", "file": "1-2-hallucination.html"},
 "137": {"name": "RAG 与幻觉边界", "file": "1-2-mitigation-rag.html"},
 "201": {"name": "上下文窗口边界", "file": "5-1.html"},
 "202": {"name": "上下文预算构成", "file": "5-1.html"},
 "203": {"name": "溢出策略取舍", "file": "5-2.html"},
 "204": {"name": "Markdown 何以胜出", "file": "6-0a.html"},
 "205": {"name": "角色即系统预设", "file": "6-1.html"},
 "206": {"name": "Prompt 万能公式", "file": "6-2.html"},
 "207": {"name": "JSON 输出工程风险", "file": "6-3.html"},
 "208": {"name": "流式与格式配合", "file": "6-4.html"},
 "209": {"name": "注入攻击的根因", "file": "prompt-attack.html"},
 "210": {"name": "防御分层拦截逻辑", "file": "prompt-defense.html"},
 "211": {"name": "工具调用安全归属", "file": "7-2.html"},
 "212": {"name": "工具描述设计", "file": "7-2b.html"},
 "213": {"name": "MCP 传输方式选型", "file": "7-2d.html"},
 "214": {"name": "KV Cache 原理", "file": "8-2.html"},
 "215": {"name": "上下文压缩四层防线", "file": "7-3b.html"},
 "216": {"name": "注入攻击类型识别", "file": "prompt-attack.html"},
 "217": {"name": "三层防御设计要点", "file": "prompt-defense.html"},
 "218": {"name": "Agent 卡死模式", "file": "7-4b.html"},
 "219": {"name": "KV Cache 缓存杀手", "file": "8-3.html"},
 "220": {"name": "多轮对话成本结构", "file": "8-1.html"},
 "221": {"name": "显式缓存的必要性", "file": "8-2b.html"},
 "222": {"name": "流式下的 Markdown 边界", "file": "6-4.html"},
 "223": {"name": "缓存与固定前缀", "file": "8-2.html"},
 "224": {"name": "模型路由省钱逻辑", "file": "8-4.html"},
 "225": {"name": "模型联网能力边界", "file": "7-2.html"},
 "226": {"name": "Agent 概念", "file": "7-1.html"},
 "227": {"name": "工具调用机制", "file": "7-2.html"},
 "228": {"name": "对话记忆原理", "file": "5-1.html"},
 "229": {"name": "Prompt 注入攻击", "file": "prompt-attack.html"},
 "230": {"name": "模型能力边界", "file": "ai-tips-boundary.html"},
 "231": {"name": "Agent 核心能力", "file": "7-1.html"},
 "232": {"name": "搜索功能的实现", "file": "7-2.html"},
 "233": {"name": "角色设定原理", "file": "6-1.html"},
 "234": {"name": "工具调用消息链路", "file": "7-2a.html"},
 "235": {"name": "多工具编排分批", "file": "7-2c.html"},
 "236": {"name": "图片计费口径", "file": "8-5.html"},
 "237": {"name": "中断恢复护栏", "file": "7-6a.html"},
 "238": {"name": "Skill 的工具边界", "file": "7-5b.html"},
 "239": {"name": "Agent 权限模式", "file": "7-4c.html"},
 "240": {"name": "语法层 Token 优化", "file": "8-6.html"},
 "241": {"name": "Harness 取舍标准", "file": "engineering-philosophy.html"},
 "242": {"name": "模型选型性价比", "file": "cost-eval.html"},
 "301": {"name": "文生图与垫图区别", "file": "9-1.html"},
 "302": {"name": "生图Prompt二次翻译", "file": "9-2.html"},
 "303": {"name": "角色一致性与参考图", "file": "9-3.html"},
 "304": {"name": "模型故障降级链", "file": "9-4.html"},
 "305": {"name": "Agent卡死模式", "file": "9-7.html"},
 "306": {"name": "防呆三层防护", "file": "9-8.html"},
 "307": {"name": "流式进度感设计", "file": "9-9.html"},
 "308": {"name": "一条消息的成本", "file": "9-10.html"},
 "309": {"name": "越长越贵越笨", "file": "9-11.html"},
 "310": {"name": "用户消息不可删", "file": "9-13.html"},
 "311": {"name": "本地与LLM压缩", "file": "9-14.html"},
 "312": {"name": "上下文与记忆区别", "file": "9-15.html"},
 "313": {"name": "记忆冲突四策略", "file": "9-17.html"},
 "314": {"name": "工具按需加载", "file": "9-20.html"},
 "315": {"name": "生图产品化清单", "file": "9-5.html"},
 "316": {"name": "压缩取舍框架", "file": "9-12.html"},
 "317": {"name": "记忆守门员筛选", "file": "9-16.html"},
 "318": {"name": "多Agent适用场景", "file": "9-23.html"},
 "319": {"name": "风险分级弹窗", "file": "9-28.html"},
 "320": {"name": "SystemPrompt分层", "file": "9-19.html"},
 "321": {"name": "并发读写规则", "file": "9-24.html"},
 "322": {"name": "Agent可观测性", "file": "9-29.html"},
 "323": {"name": "MCP双向协议", "file": "9-30.html"},
 "324": {"name": "AI自配置工具", "file": "9-32.html"},
 "325": {"name": "生产环境单轮流程", "file": "9-6.html"},
 "326": {"name": "全量注入的代价", "file": "9-18.html"},
 "327": {"name": "Skill职责定位", "file": "9-21.html"},
 "328": {"name": "Skill注入与缓存", "file": "9-22.html"},
 "329": {"name": "脑暴独立思考", "file": "9-25.html"},
 "330": {"name": "定时任务新建会话", "file": "9-26.html"},
 "331": {"name": "五种权限模式", "file": "9-27.html"},
 "332": {"name": "MCP懒连接原则", "file": "9-31.html"},
 "333": {"name": "冰山模型八层", "file": "9-final.html"},
 "334": {"name": "硬限制三道刹车", "file": "9-8.html"},
 "335": {"name": "卡死模式不报错", "file": "9-7.html"},
 "336": {"name": "任务复杂度与成本", "file": "9-10.html"},
 "337": {"name": "长对话的三个代价", "file": "9-11.html"},
 "338": {"name": "拆分Agent前三问", "file": "9-23.html"},
 "339": {"name": "读写并发耗时", "file": "9-24.html"},
 "340": {"name": "四层各自的职责", "file": "9-19.html"},
 "341": {"name": "记忆按需检索", "file": "9-18.html"},
 "342": {"name": "权限模式选择维度", "file": "9-27.html"},
 "343": {"name": "实战篇八个主题", "file": "9-summary.html"},
 "344": {"name": "角色参考图锚点", "file": "9-3.html"},
 "345": {"name": "Skill结构与优势", "file": "9-21.html"},
 "346": {"name": "动态内容与缓存", "file": "9-22.html"},
 "347": {"name": "脑暴并行耗时", "file": "9-25.html"},
 "348": {"name": "懒连接启动耗时", "file": "9-31.html"},
 "349": {"name": "产品决策的难点", "file": "9-final.html"},
 "350": {"name": "风险分级确认次数", "file": "9-28.html"},
 "401": {"name": "Workflow与Agent之别", "file": "10-1.html"},
 "402": {"name": "复杂度阶梯原则", "file": "10-1.html"},
 "403": {"name": "长任务失败模式", "file": "10-11.html"},
 "404": {"name": "编排者与并行化区别", "file": "10-2.html"},
 "405": {"name": "上下文工程方法论", "file": "10-3.html"},
 "406": {"name": "压缩的信息取舍", "file": "10-4.html"},
 "407": {"name": "子Agent架构价值", "file": "10-4.html"},
 "408": {"name": "预加载与JIT检索", "file": "10-4.html"},
 "409": {"name": "防呆设计原则", "file": "10-5.html"},
 "410": {"name": "Think Tool本质", "file": "10-6.html"},
 "411": {"name": "工具优化工作流", "file": "10-7.html"},
 "412": {"name": "评测起步建议", "file": "10-8.html"},
 "413": {"name": "代码Grader场景", "file": "10-9.html"},
 "414": {"name": "会话与上下文窗口", "file": "10-14.html"},
 "415": {"name": "五种Workflow模式", "file": "10-2.html"},
 "416": {"name": "工具描述的要素", "file": "10-5.html"},
 "417": {"name": "评测三大陷阱", "file": "10-10.html"},
 "418": {"name": "双角色Harness分工", "file": "10-12.html"},
 "419": {"name": "三类安全风险分类", "file": "10-15.html"},
 "420": {"name": "脑手分离与容错", "file": "10-13.html"},
 "421": {"name": "沙箱与凭证隔离", "file": "10-16.html"},
 "422": {"name": "上下文化检索", "file": "10-17.html"},
 "423": {"name": "最简可行工程哲学", "file": "10-final.html"},
 "424": {"name": "上下文稀缺资源", "file": "10-summary.html"},
 "425": {"name": "Agent的成本与调试", "file": "10-1.html"},
 "426": {"name": "提示链的质量门", "file": "10-2.html"},
 "427": {"name": "路由的成本优化", "file": "10-2.html"},
 "428": {"name": "并行化两个子模式", "file": "10-2.html"},
 "429": {"name": "注意力的平方代价", "file": "10-3.html"},
 "430": {"name": "系统提示词的高度", "file": "10-3.html"},
 "431": {"name": "结构化笔记的设计", "file": "10-4.html"},
 "432": {"name": "工具的非确定性", "file": "10-5.html"},
 "433": {"name": "减少格式开销", "file": "10-5.html"},
 "434": {"name": "思考工具的边界", "file": "10-6.html"},
 "435": {"name": "返回结果的精简", "file": "10-7.html"},
 "436": {"name": "试验与统计意义", "file": "10-8.html"},
 "437": {"name": "评分标准的设计", "file": "10-9.html"},
 "438": {"name": "模型识别评测", "file": "10-10.html"},
 "439": {"name": "功能清单用JSON", "file": "10-12.html"},
 "440": {"name": "脑手分离的收益", "file": "10-13.html"},
 "441": {"name": "上下文窗口构成", "file": "10-3.html"},
 "442": {"name": "五个工具设计原则", "file": "10-7.html"},
 "443": {"name": "会话日志可查询", "file": "10-14.html"},
 "444": {"name": "环境层防线手段", "file": "10-15.html"},
 "445": {"name": "三层信任层级", "file": "10-16.html"},
 "446": {"name": "思考时机的分工", "file": "10-6.html"},
 "447": {"name": "过早宣布完成", "file": "10-11.html"},
 "448": {"name": "上下文化检索代价", "file": "10-17.html"},
 "449": {"name": "脚手架假设会过时", "file": "10-final.html"},
 "450": {"name": "人工评判器定位", "file": "10-9.html"},
 "501": {"name": "递归自我改进路径", "file": "11-1.html"},
 "502": {"name": "Harness 的定义", "file": "11-1.html"},
 "503": {"name": "工作流自动化模式", "file": "11-2.html"},
 "504": {"name": "上下文与文件分工", "file": "11-2.html"},
 "505": {"name": "ACE 三组件协作", "file": "11-3.html"},
 "506": {"name": "ACE 增量更新设计", "file": "11-3.html"},
 "507": {"name": "MCE 双层优化", "file": "11-3.html"},
 "508": {"name": "Meta-Harness 对象", "file": "11-3.html"},
 "509": {"name": "AFlow 树搜索", "file": "11-4.html"},
 "510": {"name": "Autodata 难度信号", "file": "11-4.html"},
 "511": {"name": "STOP 递归改善器", "file": "11-5.html"},
 "512": {"name": "Self-Harness 验证", "file": "11-5.html"},
 "513": {"name": "DGM 自我进化", "file": "11-6.html"},
 "514": {"name": "奖励黑客防范", "file": "11-7.html"},
 "515": {"name": "Harness 三大模式", "file": "11-2.html"},
 "516": {"name": "ADAS 元搜索机制", "file": "11-4.html"},
 "517": {"name": "进化搜索契合条件", "file": "11-6.html"},
 "518": {"name": "七道关挑战清单", "file": "11-7.html"},
 "519": {"name": "自动研究失败模式", "file": "11-7.html"},
 "520": {"name": "Harness 层的价值", "file": "11-1.html"},
 "521": {"name": "上下文膨胀风险", "file": "11-3.html"},
 "522": {"name": "STOP 基座门槛", "file": "11-5.html"},
 "523": {"name": "SIA 联合优化风险", "file": "11-6.html"},
 "524": {"name": "人类角色定位", "file": "11-7.html"},
 "525": {"name": "优化对象五级阶梯", "file": "11-3.html"},
 "526": {"name": "Prompt 工程类比", "file": "11-1.html"},
 "527": {"name": "父 Agent 进程管理", "file": "11-2.html"},
 "528": {"name": "子 Agent 并发协调", "file": "11-2.html"},
 "529": {"name": "MCE 上下文函数", "file": "11-3.html"},
 "530": {"name": "Meta-Harness 历史访问", "file": "11-3.html"},
 "531": {"name": "AFlow 搜索终止条件", "file": "11-4.html"},
 "532": {"name": "AI Scientist 评审环节", "file": "11-4.html"},
 "533": {"name": "STOP 种子改善器输入", "file": "11-5.html"},
 "534": {"name": "Weakness Mining 产出", "file": "11-5.html"},
 "535": {"name": "Self-Harness 改进对象", "file": "11-5.html"},
 "536": {"name": "DGM 父代选择策略", "file": "11-6.html"},
 "537": {"name": "Promptbreeder 元进化", "file": "11-6.html"},
 "538": {"name": "SIA 角色分工", "file": "11-6.html"},
 "539": {"name": "长期成功挑战", "file": "11-7.html"},
 "540": {"name": "负面结果保存要求", "file": "11-7.html"},
 "541": {"name": "AlphaEvolve 设计要素", "file": "11-6.html"},
 "542": {"name": "进化搜索不适用场景", "file": "11-6.html"},
 "543": {"name": "Harness Proposal 输入", "file": "11-5.html"},
 "544": {"name": "MCE 工程实现", "file": "11-3.html"},
 "545": {"name": "文件系统记忆要点", "file": "11-2.html"},
 "546": {"name": "Harness 正反馈循环", "file": "11-1.html"},
 "547": {"name": "Meta-Harness 实验起点", "file": "11-3.html"},
 "548": {"name": "DGM 实验数字", "file": "11-6.html"},
 "549": {"name": "上下文工程定位", "file": "11-7.html"},
 "550": {"name": "纯循环架构失效点", "file": "11-2.html"},
 "601": {"name": "工作区成员与主轴", "file": "12-1.html"},
 "602": {"name": "三大Actor分工", "file": "12-4.html"},
 "603": {"name": "入口与运行分支", "file": "12-3.html"},
 "604": {"name": "取消边界与不可变", "file": "12-4.html"},
 "605": {"name": "压缩策略默认值", "file": "12-5.html"},
 "606": {"name": "阈值等号边界", "file": "12-11.html"},
 "607": {"name": "工具只读默认值", "file": "12-8.html"},
 "608": {"name": "预设注册可见性", "file": "12-7.html"},
 "609": {"name": "动态MCP元工具", "file": "12-9.html"},
 "610": {"name": "检索降级策略", "file": "12-12.html"},
 "611": {"name": "记忆整理触发门控", "file": "12-13.html"},
 "612": {"name": "沙箱五种档位", "file": "12-17.html"},
 "613": {"name": "钩子失败语义", "file": "12-19.html"},
 "614": {"name": "子Agent隔离恢复", "file": "12-15.html"},
 "615": {"name": "工具授权链路", "file": "12-18.html"},
 "616": {"name": "两段式压缩机制", "file": "12-5.html"},
 "617": {"name": "混合检索流水线", "file": "12-12.html"},
 "618": {"name": "自定义沙箱规则", "file": "12-17.html"},
 "619": {"name": "MCP工程细节", "file": "12-20.html"},
 "620": {"name": "只读与审批边界", "file": "12-8.html"},
 "621": {"name": "Token本地估算", "file": "12-11.html"},
 "622": {"name": "插件信任边界", "file": "12-23.html"},
 "623": {"name": "梦境锁与幂等", "file": "12-13.html"},
 "624": {"name": "对照证据口径", "file": "12-22.html"},
 "625": {"name": "事实与推断分界", "file": "12-2.html"},
 "626": {"name": "两级运行时边界", "file": "12-4.html"},
 "627": {"name": "上下文序列化来源", "file": "12-6.html"},
 "628": {"name": "模板覆盖三变体", "file": "12-6.html"},
 "629": {"name": "归一化字段清单", "file": "12-10.html"},
 "630": {"name": "元数据合约版本", "file": "12-10.html"},
 "631": {"name": "有效运行时字段", "file": "12-14.html"},
 "632": {"name": "逐字段合并优先级", "file": "12-14.html"},
 "633": {"name": "人格失败关闭", "file": "12-14.html"},
 "634": {"name": "协调器启动方式", "file": "12-16.html"},
 "635": {"name": "插件来源与启用", "file": "12-21.html"},
 "636": {"name": "目录扫描与清单", "file": "12-21.html"},
 "637": {"name": "结课评审权重", "file": "12-24.html"},
 "638": {"name": "恢复的上下文上限", "file": "12-15.html"},
 "639": {"name": "工具模型可见性", "file": "12-20.html"},
 "640": {"name": "钩子阻断能力", "file": "12-19.html"},
 "641": {"name": "稳定投影取舍", "file": "12-10.html"},
 "642": {"name": "多Agent协调层", "file": "12-16.html"},
 "643": {"name": "插件三道门槛", "file": "12-21.html"},
 "644": {"name": "沙箱档位能力差异", "file": "12-17.html"},
 "645": {"name": "梦境成功边界", "file": "12-13.html"},
 "646": {"name": "选型证据分级", "file": "12-2.html"},
 "647": {"name": "结课评审否决项", "file": "12-24.html"},
 "648": {"name": "构建主机边界", "file": "12-23.html"},
 "649": {"name": "预留空间阈值", "file": "12-11.html"},
 "650": {"name": "命名空间覆盖面", "file": "12-9.html"},
 "701": {"name": "理念与事故根源", "file": "vibe-1.html"},
 "702": {"name": "Rule 注入机制", "file": "vibe-1.html"},
 "703": {"name": "四步流程与断点", "file": "vibe-2.html"},
 "704": {"name": "批量修改断点", "file": "vibe-2.html"},
 "705": {"name": "PlayGround 定位", "file": "vibe-3.html"},
 "706": {"name": "注释三要素", "file": "vibe-4.html"},
 "707": {"name": "调试铁律先 Log", "file": "vibe-5.html"},
 "708": {"name": "真实接口交付线", "file": "vibe-5.html"},
 "709": {"name": "拒绝简版的动机", "file": "vibe-6.html"},
 "710": {"name": "拆分决策权归属", "file": "vibe-6.html"},
 "711": {"name": "文档分诊边界", "file": "vibe-7.html"},
 "712": {"name": "数据格式三分法", "file": "vibe-8.html"},
 "713": {"name": "diff 审查意图", "file": "vibe-9.html"},
 "714": {"name": "上下文漂移成因", "file": "vibe-10.html"},
 "715": {"name": "修改计划三要素", "file": "vibe-2.html"},
 "716": {"name": "代码保护规则", "file": "vibe-4.html"},
 "717": {"name": "修复前三问", "file": "vibe-5.html"},
 "718": {"name": "四份文档分工", "file": "vibe-7.html"},
 "719": {"name": "破坏性操作三闸", "file": "vibe-9.html"},
 "720": {"name": "demo 只增不删", "file": "vibe-3.html"},
 "721": {"name": "禁止分期规划", "file": "vibe-6.html"},
 "722": {"name": "输入法误发送坑", "file": "vibe-8.html"},
 "723": {"name": "凭据泄露处理", "file": "vibe-9.html"},
 "724": {"name": "规则适配改造", "file": "vibe-final.html"},
 "725": {"name": "Rule 生效方式配置", "file": "vibe-1.html"},
 "726": {"name": "三个规则文件分工", "file": "vibe-1.html"},
 "727": {"name": "新功能查重规则", "file": "vibe-2.html"},
 "728": {"name": "流程首步思考提问", "file": "vibe-2.html"},
 "729": {"name": "组件动效创建时机", "file": "vibe-3.html"},
 "730": {"name": "提示词摊开可调", "file": "vibe-3.html"},
 "731": {"name": "禁止空 catch", "file": "vibe-4.html"},
 "732": {"name": "设计意图写什么", "file": "vibe-4.html"},
 "733": {"name": "修复后声明影响范围", "file": "vibe-5.html"},
 "734": {"name": "单元测试交付线", "file": "vibe-5.html"},
 "735": {"name": "技术债成本曲线", "file": "vibe-6.html"},
 "736": {"name": "完整实现评估方式", "file": "vibe-6.html"},
 "737": {"name": "改动记录表格字段", "file": "vibe-7.html"},
 "738": {"name": "图像生成超时配置", "file": "vibe-8.html"},
 "739": {"name": "网络失败代理回退", "file": "vibe-8.html"},
 "740": {"name": "发布通道走 GitHub", "file": "vibe-9.html"},
 "741": {"name": "方法论写入原则", "file": "vibe-7.html"},
 "742": {"name": "技术栈与品味规则", "file": "vibe-8.html"},
 "743": {"name": "diff 风险判定", "file": "vibe-9.html"},
 "744": {"name": "违禁模式清单", "file": "vibe-10.html"},
 "745": {"name": "规则落地与维护", "file": "vibe-final.html"},
 "746": {"name": "历史沿革初始需求", "file": "vibe-7.html"},
 "747": {"name": "响应流式要求", "file": "vibe-8.html"},
 "748": {"name": "风险发现后暂停发版", "file": "vibe-9.html"},
 "749": {"name": "目标以最新为准", "file": "vibe-10.html"},
 "750": {"name": "并行编辑先重读", "file": "vibe-10.html"}
};
