/* 考点总表：考点组编号 → 考点名 + 对应课节。

   题目本身按篇章拆在 exam-data-1.js ~ exam-data-7.js 里，本文件只留考点表。
   交卷后前端按考点组聚合对错并上报，米羊个人中心据此展示薄弱点和补课入口。
   服务端 auth-service.py 解析本表（和 course-data.js 同款 mtime 热加载），
   改考点名或补课链接只动这里，不用重启服务。

   编号规则：1-22 是早期综合卷的考点（题目已并入第一、二篇章，编号保留给历史成绩兜底）；
   1xx-5xx 对应大模型原理到自我改进五个主线篇章，7xx 对应协作方法论篇（Vibe Coding），6xx 对应 Grok Build 专题。
   6xx / 7xx 的百位与篇章序号对不上，是 2026-08-09 篇章重排留下的：Grok Build 降级为
   选修专题、Vibe Coding 补位原第六篇章（现协作方法论篇），但考点编号已经写进学员的历史成绩和薄弱点记录里，
   重编号会让这些数据全部对不上，所以只改展示文案，不动编号。 */
window.EXAM_TOPICS = {
 "1": {"name": "Token 機率生成機制", "file": "1-2-base.html"},
 "2": {"name": "模型聯網能力邊界", "file": "7-2.html"},
 "3": {"name": "幻覺的成因", "file": "1-2-hallucination.html"},
 "4": {"name": "RAG 的核心作用", "file": "1-2-mitigation-rag.html"},
 "5": {"name": "RAG 的侷限", "file": "1-2-mitigation-rag.html"},
 "6": {"name": "Agent 概念", "file": "7-1.html"},
 "7": {"name": "工具呼叫機制", "file": "7-2.html"},
 "8": {"name": "Temperature 取樣", "file": "1-2-mitigation-temp.html"},
 "9": {"name": "提示詞起效原理", "file": "1-2-prompt-power.html"},
 "10": {"name": "對話記憶原理", "file": "5-1.html"},
 "11": {"name": "Prompt 注入攻擊", "file": "prompt-attack.html"},
 "12": {"name": "幻覺與創意的關係", "file": "1-2-hallucination.html"},
 "13": {"name": "技術棧底層機制", "file": "1-2-base.html"},
 "14": {"name": "模型能力邊界", "file": "ai-tips-boundary.html"},
 "15": {"name": "Agent 核心能力", "file": "7-1.html"},
 "16": {"name": "幻覺緩解手段", "file": "summary-1b.html"},
 "17": {"name": "大模型基本認知", "file": "summary-1.html"},
 "18": {"name": "RAG 工作流程", "file": "1-2-mitigation-rag.html"},
 "19": {"name": "搜尋功能的實現", "file": "7-2.html"},
 "20": {"name": "幻覺的內在性", "file": "1-2-hallucination.html"},
 "21": {"name": "RAG 與幻覺邊界", "file": "1-2-mitigation-rag.html"},
 "22": {"name": "角色設定原理", "file": "6-1.html"},
 "101": {"name": "SFT 解決的問題", "file": "1-2-sft.html"},
 "102": {"name": "Base 模型行為特徵", "file": "1-2-base.html"},
 "103": {"name": "Chat Template 結構", "file": "1-2-sft.html"},
 "104": {"name": "對話即補全本質", "file": "1-2-api.html"},
 "105": {"name": "偽造聊天記錄實驗", "file": "1-2-fake-chat.html"},
 "106": {"name": "訓練與推理的區別", "file": "train-vs-infer.html"},
 "107": {"name": "參數與上下文之別", "file": "1-2-hallucination.html"},
 "108": {"name": "提示詞等效訓練機制", "file": "1-2-prompt-power.html"},
 "109": {"name": "Temperature 縮放機制", "file": "1-2-mitigation-temp.html"},
 "110": {"name": "場景化取樣參數", "file": "1-2-mitigation-temp.html"},
 "111": {"name": "幻覺型別判別", "file": "summary-1.html"},
 "112": {"name": "GPT 預訓練躍進", "file": "1-2-gpt.html"},
 "113": {"name": "Token 與分詞", "file": "1-2-vocab.html"},
 "114": {"name": "RAG 意圖過濾優化", "file": "rag-advanced.html"},
 "115": {"name": "Prompt 約束的邊界", "file": "1-2-mitigation-prompt.html"},
 "116": {"name": "評測與稽核環節", "file": "1-2-mitigation-eval.html"},
 "117": {"name": "訓練資料規模認知", "file": "training-data.html"},
 "118": {"name": "RAG 成本與優化", "file": "rag-advanced.html"},
 "119": {"name": "緩解策略場景匹配", "file": "summary-1b.html"},
 "120": {"name": "參數凍結與對話", "file": "train-vs-infer.html"},
 "121": {"name": "SFT 的能力邊界", "file": "1-2-sft.html"},
 "122": {"name": "溫度與知識邊界", "file": "1-2-mitigation-temp.html"},
 "123": {"name": "幻覺率指標管理", "file": "1-2-mitigation-eval.html"},
 "124": {"name": "RAG 檢索風險", "file": "1-2-mitigation-rag.html"},
 "125": {"name": "Token 機率生成機制", "file": "1-2-base.html"},
 "126": {"name": "幻覺的成因", "file": "1-2-hallucination.html"},
 "127": {"name": "RAG 的核心作用", "file": "1-2-mitigation-rag.html"},
 "128": {"name": "RAG 的侷限", "file": "1-2-mitigation-rag.html"},
 "129": {"name": "Temperature 取樣", "file": "1-2-mitigation-temp.html"},
 "130": {"name": "提示詞起效原理", "file": "1-2-prompt-power.html"},
 "131": {"name": "幻覺與創意的關係", "file": "1-2-hallucination.html"},
 "132": {"name": "技術棧底層機制", "file": "1-2-base.html"},
 "133": {"name": "幻覺緩解手段", "file": "summary-1b.html"},
 "134": {"name": "大模型基本認知", "file": "summary-1.html"},
 "135": {"name": "RAG 工作流程", "file": "1-2-mitigation-rag.html"},
 "136": {"name": "幻覺的內在性", "file": "1-2-hallucination.html"},
 "137": {"name": "RAG 與幻覺邊界", "file": "1-2-mitigation-rag.html"},
 "201": {"name": "上下文視窗邊界", "file": "5-1.html"},
 "202": {"name": "上下文預算構成", "file": "5-1.html"},
 "203": {"name": "溢位策略取捨", "file": "5-2.html"},
 "204": {"name": "Markdown 何以勝出", "file": "6-0a.html"},
 "205": {"name": "角色即系統預設", "file": "6-1.html"},
 "206": {"name": "Prompt 萬能公式", "file": "6-2.html"},
 "207": {"name": "JSON 輸出工程風險", "file": "6-3.html"},
 "208": {"name": "流式與格式配合", "file": "6-4.html"},
 "209": {"name": "注入攻擊的根因", "file": "prompt-attack.html"},
 "210": {"name": "防禦分層攔截邏輯", "file": "prompt-defense.html"},
 "211": {"name": "工具呼叫安全歸屬", "file": "7-2.html"},
 "212": {"name": "工具描述設計", "file": "7-2b.html"},
 "213": {"name": "MCP 傳輸方式選型", "file": "7-2d.html"},
 "214": {"name": "KV Cache 原理", "file": "8-2.html"},
 "215": {"name": "上下文壓縮四層防線", "file": "7-3b.html"},
 "216": {"name": "注入攻擊型別識別", "file": "prompt-attack.html"},
 "217": {"name": "三層防禦設計要點", "file": "prompt-defense.html"},
 "218": {"name": "Agent 卡死模式", "file": "7-4b.html"},
 "219": {"name": "KV Cache 快取殺手", "file": "8-3.html"},
 "220": {"name": "多輪對話成本結構", "file": "8-1.html"},
 "221": {"name": "顯式快取的必要性", "file": "8-2b.html"},
 "222": {"name": "流式下的 Markdown 邊界", "file": "6-4.html"},
 "223": {"name": "快取與固定字首", "file": "8-2.html"},
 "224": {"name": "模型路由省錢邏輯", "file": "8-4.html"},
 "225": {"name": "模型聯網能力邊界", "file": "7-2.html"},
 "226": {"name": "Agent 概念", "file": "7-1.html"},
 "227": {"name": "工具呼叫機制", "file": "7-2.html"},
 "228": {"name": "對話記憶原理", "file": "5-1.html"},
 "229": {"name": "Prompt 注入攻擊", "file": "prompt-attack.html"},
 "230": {"name": "模型能力邊界", "file": "ai-tips-boundary.html"},
 "231": {"name": "Agent 核心能力", "file": "7-1.html"},
 "232": {"name": "搜尋功能的實現", "file": "7-2.html"},
 "233": {"name": "角色設定原理", "file": "6-1.html"},
 "234": {"name": "工具呼叫訊息鏈路", "file": "7-2a.html"},
 "235": {"name": "多工具編排分批", "file": "7-2c.html"},
 "236": {"name": "圖片計費口徑", "file": "8-5.html"},
 "237": {"name": "中斷恢復護欄", "file": "7-6a.html"},
 "238": {"name": "Skill 的工具邊界", "file": "7-5b.html"},
 "239": {"name": "Agent 權限模式", "file": "7-4c.html"},
 "240": {"name": "語法層 Token 優化", "file": "8-6.html"},
 "241": {"name": "Harness 取捨標準", "file": "engineering-philosophy.html"},
 "242": {"name": "模型選型性價比", "file": "cost-eval.html"},
 "301": {"name": "文生圖與墊圖區別", "file": "9-1.html"},
 "302": {"name": "生圖Prompt二次翻譯", "file": "9-2.html"},
 "303": {"name": "角色一致性與參考圖", "file": "9-3.html"},
 "304": {"name": "模型故障降級鏈", "file": "9-4.html"},
 "305": {"name": "Agent卡死模式", "file": "9-7.html"},
 "306": {"name": "防呆三層防護", "file": "9-8.html"},
 "307": {"name": "流式進度感設計", "file": "9-9.html"},
 "308": {"name": "一條訊息的成本", "file": "9-10.html"},
 "309": {"name": "越長越貴越笨", "file": "9-11.html"},
 "310": {"name": "使用者訊息不可刪", "file": "9-13.html"},
 "311": {"name": "本地與LLM壓縮", "file": "9-14.html"},
 "312": {"name": "上下文與記憶區別", "file": "9-15.html"},
 "313": {"name": "記憶衝突四策略", "file": "9-17.html"},
 "314": {"name": "工具按需載入", "file": "9-20.html"},
 "315": {"name": "生圖產品化清單", "file": "9-5.html"},
 "316": {"name": "壓縮取捨框架", "file": "9-12.html"},
 "317": {"name": "記憶守門員篩選", "file": "9-16.html"},
 "318": {"name": "多Agent適用場景", "file": "9-23.html"},
 "319": {"name": "風險分級彈窗", "file": "9-28.html"},
 "320": {"name": "SystemPrompt分層", "file": "9-19.html"},
 "321": {"name": "併發讀寫規則", "file": "9-24.html"},
 "322": {"name": "Agent可觀測性", "file": "9-29.html"},
 "323": {"name": "MCP雙向協議", "file": "9-30.html"},
 "324": {"name": "AI自配置工具", "file": "9-32.html"},
 "325": {"name": "生產環境單輪流程", "file": "9-6.html"},
 "326": {"name": "全量注入的代價", "file": "9-18.html"},
 "327": {"name": "Skill職責定位", "file": "9-21.html"},
 "328": {"name": "Skill注入與快取", "file": "9-22.html"},
 "329": {"name": "腦暴獨立思考", "file": "9-25.html"},
 "330": {"name": "定時任務新建會話", "file": "9-26.html"},
 "331": {"name": "五種權限模式", "file": "9-27.html"},
 "332": {"name": "MCP懶連線原則", "file": "9-31.html"},
 "333": {"name": "冰山模型八層", "file": "9-final.html"},
 "334": {"name": "硬限制三道剎車", "file": "9-8.html"},
 "335": {"name": "卡死模式不報錯", "file": "9-7.html"},
 "336": {"name": "任務複雜度與成本", "file": "9-10.html"},
 "337": {"name": "長對話的三個代價", "file": "9-11.html"},
 "338": {"name": "拆分Agent前三問", "file": "9-23.html"},
 "339": {"name": "讀寫併發耗時", "file": "9-24.html"},
 "340": {"name": "四層各自的職責", "file": "9-19.html"},
 "341": {"name": "記憶按需檢索", "file": "9-18.html"},
 "342": {"name": "權限模式選擇維度", "file": "9-27.html"},
 "343": {"name": "實戰篇八個主題", "file": "9-summary.html"},
 "344": {"name": "角色參考圖錨點", "file": "9-3.html"},
 "345": {"name": "Skill結構與優勢", "file": "9-21.html"},
 "346": {"name": "動態內容與快取", "file": "9-22.html"},
 "347": {"name": "腦暴並行耗時", "file": "9-25.html"},
 "348": {"name": "懶連線啟動耗時", "file": "9-31.html"},
 "349": {"name": "產品決策的難點", "file": "9-final.html"},
 "350": {"name": "風險分級確認次數", "file": "9-28.html"},
 "401": {"name": "Workflow與Agent之別", "file": "10-1.html"},
 "402": {"name": "複雜度階梯原則", "file": "10-1.html"},
 "403": {"name": "長任務失敗模式", "file": "10-11.html"},
 "404": {"name": "編排者與並行化區別", "file": "10-2.html"},
 "405": {"name": "上下文工程方法論", "file": "10-3.html"},
 "406": {"name": "壓縮的資訊取捨", "file": "10-4.html"},
 "407": {"name": "子Agent架構價值", "file": "10-4.html"},
 "408": {"name": "預載入與JIT檢索", "file": "10-4.html"},
 "409": {"name": "防呆設計原則", "file": "10-5.html"},
 "410": {"name": "Think Tool本質", "file": "10-6.html"},
 "411": {"name": "工具優化工作流", "file": "10-7.html"},
 "412": {"name": "評測起步建議", "file": "10-8.html"},
 "413": {"name": "程式碼Grader場景", "file": "10-9.html"},
 "414": {"name": "會話與上下文視窗", "file": "10-14.html"},
 "415": {"name": "五種Workflow模式", "file": "10-2.html"},
 "416": {"name": "工具描述的要素", "file": "10-5.html"},
 "417": {"name": "評測三大陷阱", "file": "10-10.html"},
 "418": {"name": "雙角色Harness分工", "file": "10-12.html"},
 "419": {"name": "三類安全風險分類", "file": "10-15.html"},
 "420": {"name": "腦手分離與容錯", "file": "10-13.html"},
 "421": {"name": "沙箱與憑證隔離", "file": "10-16.html"},
 "422": {"name": "上下文化檢索", "file": "10-17.html"},
 "423": {"name": "最簡可行工程哲學", "file": "10-final.html"},
 "424": {"name": "上下文稀缺資源", "file": "10-summary.html"},
 "425": {"name": "Agent的成本與除錯", "file": "10-1.html"},
 "426": {"name": "提示鏈的品質門", "file": "10-2.html"},
 "427": {"name": "路由的成本優化", "file": "10-2.html"},
 "428": {"name": "並行化兩個子模式", "file": "10-2.html"},
 "429": {"name": "注意力的平方代價", "file": "10-3.html"},
 "430": {"name": "系統提示詞的高度", "file": "10-3.html"},
 "431": {"name": "結構化筆記的設計", "file": "10-4.html"},
 "432": {"name": "工具的非確定性", "file": "10-5.html"},
 "433": {"name": "減少格式開銷", "file": "10-5.html"},
 "434": {"name": "思考工具的邊界", "file": "10-6.html"},
 "435": {"name": "返回結果的精簡", "file": "10-7.html"},
 "436": {"name": "試驗與統計意義", "file": "10-8.html"},
 "437": {"name": "評分標準的設計", "file": "10-9.html"},
 "438": {"name": "模型識別評測", "file": "10-10.html"},
 "439": {"name": "功能清單用JSON", "file": "10-12.html"},
 "440": {"name": "腦手分離的收益", "file": "10-13.html"},
 "441": {"name": "上下文視窗構成", "file": "10-3.html"},
 "442": {"name": "五個工具設計原則", "file": "10-7.html"},
 "443": {"name": "會話日誌可查詢", "file": "10-14.html"},
 "444": {"name": "環境層防線手段", "file": "10-15.html"},
 "445": {"name": "三層信任層級", "file": "10-16.html"},
 "446": {"name": "思考時機的分工", "file": "10-6.html"},
 "447": {"name": "過早宣佈完成", "file": "10-11.html"},
 "448": {"name": "上下文化檢索代價", "file": "10-17.html"},
 "449": {"name": "腳手架假設會過時", "file": "10-final.html"},
 "450": {"name": "人工評判器定位", "file": "10-9.html"},
 "501": {"name": "遞迴自我改進路徑", "file": "11-1.html"},
 "502": {"name": "Harness 的定義", "file": "11-1.html"},
 "503": {"name": "工作流自動化模式", "file": "11-2.html"},
 "504": {"name": "上下文與檔案分工", "file": "11-2.html"},
 "505": {"name": "ACE 三元件協作", "file": "11-3.html"},
 "506": {"name": "ACE 增量更新設計", "file": "11-3.html"},
 "507": {"name": "MCE 雙層優化", "file": "11-3.html"},
 "508": {"name": "Meta-Harness 物件", "file": "11-3.html"},
 "509": {"name": "AFlow 樹搜尋", "file": "11-4.html"},
 "510": {"name": "Autodata 難度訊號", "file": "11-4.html"},
 "511": {"name": "STOP 遞迴改善器", "file": "11-5.html"},
 "512": {"name": "Self-Harness 驗證", "file": "11-5.html"},
 "513": {"name": "DGM 自我進化", "file": "11-6.html"},
 "514": {"name": "獎勵駭客防範", "file": "11-7.html"},
 "515": {"name": "Harness 三大模式", "file": "11-2.html"},
 "516": {"name": "ADAS 元搜尋機制", "file": "11-4.html"},
 "517": {"name": "進化搜尋契合條件", "file": "11-6.html"},
 "518": {"name": "七道關挑戰清單", "file": "11-7.html"},
 "519": {"name": "自動研究失敗模式", "file": "11-7.html"},
 "520": {"name": "Harness 層的價值", "file": "11-1.html"},
 "521": {"name": "上下文膨脹風險", "file": "11-3.html"},
 "522": {"name": "STOP 基座門檻", "file": "11-5.html"},
 "523": {"name": "SIA 聯合優化風險", "file": "11-6.html"},
 "524": {"name": "人類角色定位", "file": "11-7.html"},
 "525": {"name": "優化物件五級階梯", "file": "11-3.html"},
 "526": {"name": "Prompt 工程類比", "file": "11-1.html"},
 "527": {"name": "父 Agent 程序管理", "file": "11-2.html"},
 "528": {"name": "子 Agent 併發協調", "file": "11-2.html"},
 "529": {"name": "MCE 上下文函式", "file": "11-3.html"},
 "530": {"name": "Meta-Harness 歷史訪問", "file": "11-3.html"},
 "531": {"name": "AFlow 搜尋終止條件", "file": "11-4.html"},
 "532": {"name": "AI Scientist 評審環節", "file": "11-4.html"},
 "533": {"name": "STOP 種子改善器輸入", "file": "11-5.html"},
 "534": {"name": "Weakness Mining 產出", "file": "11-5.html"},
 "535": {"name": "Self-Harness 改進物件", "file": "11-5.html"},
 "536": {"name": "DGM 父代選擇策略", "file": "11-6.html"},
 "537": {"name": "Promptbreeder 元進化", "file": "11-6.html"},
 "538": {"name": "SIA 角色分工", "file": "11-6.html"},
 "539": {"name": "長期成功挑戰", "file": "11-7.html"},
 "540": {"name": "負面結果儲存要求", "file": "11-7.html"},
 "541": {"name": "AlphaEvolve 設計要素", "file": "11-6.html"},
 "542": {"name": "進化搜尋不適用場景", "file": "11-6.html"},
 "543": {"name": "Harness Proposal 輸入", "file": "11-5.html"},
 "544": {"name": "MCE 工程實現", "file": "11-3.html"},
 "545": {"name": "檔案系統記憶要點", "file": "11-2.html"},
 "546": {"name": "Harness 正回饋迴圈", "file": "11-1.html"},
 "547": {"name": "Meta-Harness 實驗起點", "file": "11-3.html"},
 "548": {"name": "DGM 實驗數字", "file": "11-6.html"},
 "549": {"name": "上下文工程定位", "file": "11-7.html"},
 "550": {"name": "純迴圈架構失效點", "file": "11-2.html"},
 "601": {"name": "工作區成員與主軸", "file": "12-1.html"},
 "602": {"name": "三大Actor分工", "file": "12-4.html"},
 "603": {"name": "入口與執行分支", "file": "12-3.html"},
 "604": {"name": "取消邊界與不可變", "file": "12-4.html"},
 "605": {"name": "壓縮策略預設值", "file": "12-5.html"},
 "606": {"name": "閾值等號邊界", "file": "12-11.html"},
 "607": {"name": "工具只讀預設值", "file": "12-8.html"},
 "608": {"name": "預設註冊可見性", "file": "12-7.html"},
 "609": {"name": "動態MCP元工具", "file": "12-9.html"},
 "610": {"name": "檢索降級策略", "file": "12-12.html"},
 "611": {"name": "記憶整理觸發門控", "file": "12-13.html"},
 "612": {"name": "沙箱五種檔位", "file": "12-17.html"},
 "613": {"name": "鉤子失敗語義", "file": "12-19.html"},
 "614": {"name": "子Agent隔離恢復", "file": "12-15.html"},
 "615": {"name": "工具授權鏈路", "file": "12-18.html"},
 "616": {"name": "兩段式壓縮機制", "file": "12-5.html"},
 "617": {"name": "混合檢索流水線", "file": "12-12.html"},
 "618": {"name": "自訂沙箱規則", "file": "12-17.html"},
 "619": {"name": "MCP工程細節", "file": "12-20.html"},
 "620": {"name": "只讀與審批邊界", "file": "12-8.html"},
 "621": {"name": "Token本地估算", "file": "12-11.html"},
 "622": {"name": "外掛信任邊界", "file": "12-23.html"},
 "623": {"name": "夢境鎖與冪等", "file": "12-13.html"},
 "624": {"name": "對照證據口徑", "file": "12-22.html"},
 "625": {"name": "事實與推斷分界", "file": "12-2.html"},
 "626": {"name": "兩級執行時邊界", "file": "12-4.html"},
 "627": {"name": "上下文序列化來源", "file": "12-6.html"},
 "628": {"name": "模板覆蓋三變體", "file": "12-6.html"},
 "629": {"name": "歸一化欄位清單", "file": "12-10.html"},
 "630": {"name": "中繼資料合約版本", "file": "12-10.html"},
 "631": {"name": "有效執行時欄位", "file": "12-14.html"},
 "632": {"name": "逐欄位合併優先順序", "file": "12-14.html"},
 "633": {"name": "人格失敗關閉", "file": "12-14.html"},
 "634": {"name": "協調器啟動方式", "file": "12-16.html"},
 "635": {"name": "外掛來源與啟用", "file": "12-21.html"},
 "636": {"name": "目錄掃描與清單", "file": "12-21.html"},
 "637": {"name": "結課評審權重", "file": "12-24.html"},
 "638": {"name": "恢復的上下文上限", "file": "12-15.html"},
 "639": {"name": "工具模型可見性", "file": "12-20.html"},
 "640": {"name": "鉤子阻斷能力", "file": "12-19.html"},
 "641": {"name": "穩定投影取捨", "file": "12-10.html"},
 "642": {"name": "多Agent協調層", "file": "12-16.html"},
 "643": {"name": "外掛三道門檻", "file": "12-21.html"},
 "644": {"name": "沙箱檔位能力差異", "file": "12-17.html"},
 "645": {"name": "夢境成功邊界", "file": "12-13.html"},
 "646": {"name": "選型證據分級", "file": "12-2.html"},
 "647": {"name": "結課評審否決項", "file": "12-24.html"},
 "648": {"name": "構建主機邊界", "file": "12-23.html"},
 "649": {"name": "預留空間閾值", "file": "12-11.html"},
 "650": {"name": "名稱空間覆蓋面", "file": "12-9.html"},
 "701": {"name": "理念與事故根源", "file": "vibe-1.html"},
 "702": {"name": "Rule 注入機制", "file": "vibe-1.html"},
 "703": {"name": "四步流程與斷點", "file": "vibe-2.html"},
 "704": {"name": "批次修改斷點", "file": "vibe-2.html"},
 "705": {"name": "PlayGround 定位", "file": "vibe-3.html"},
 "706": {"name": "註釋三要素", "file": "vibe-4.html"},
 "707": {"name": "除錯鐵律先 Log", "file": "vibe-5.html"},
 "708": {"name": "真實介面交付線", "file": "vibe-5.html"},
 "709": {"name": "拒絕簡版的動機", "file": "vibe-6.html"},
 "710": {"name": "拆分決策權歸屬", "file": "vibe-6.html"},
 "711": {"name": "文件分診邊界", "file": "vibe-7.html"},
 "712": {"name": "資料格式三分法", "file": "vibe-8.html"},
 "713": {"name": "diff 審查意圖", "file": "vibe-9.html"},
 "714": {"name": "上下文漂移成因", "file": "vibe-10.html"},
 "715": {"name": "修改計劃三要素", "file": "vibe-2.html"},
 "716": {"name": "程式碼保護規則", "file": "vibe-4.html"},
 "717": {"name": "修復前三問", "file": "vibe-5.html"},
 "718": {"name": "四份文件分工", "file": "vibe-7.html"},
 "719": {"name": "破壞性操作三閘", "file": "vibe-9.html"},
 "720": {"name": "demo 只增不刪", "file": "vibe-3.html"},
 "721": {"name": "禁止分期規劃", "file": "vibe-6.html"},
 "722": {"name": "輸入法誤傳送坑", "file": "vibe-8.html"},
 "723": {"name": "憑據洩露處理", "file": "vibe-9.html"},
 "724": {"name": "規則適配改造", "file": "vibe-final.html"},
 "725": {"name": "Rule 生效方式配置", "file": "vibe-1.html"},
 "726": {"name": "三個規則檔案分工", "file": "vibe-1.html"},
 "727": {"name": "新功能查重規則", "file": "vibe-2.html"},
 "728": {"name": "流程首步思考提問", "file": "vibe-2.html"},
 "729": {"name": "元件動效建立時機", "file": "vibe-3.html"},
 "730": {"name": "提示詞攤開可調", "file": "vibe-3.html"},
 "731": {"name": "禁止空 catch", "file": "vibe-4.html"},
 "732": {"name": "設計意圖寫什麼", "file": "vibe-4.html"},
 "733": {"name": "修復後宣告影響範圍", "file": "vibe-5.html"},
 "734": {"name": "單元測試交付線", "file": "vibe-5.html"},
 "735": {"name": "技術債成本曲線", "file": "vibe-6.html"},
 "736": {"name": "完整實現評估方式", "file": "vibe-6.html"},
 "737": {"name": "改動記錄表格欄位", "file": "vibe-7.html"},
 "738": {"name": "圖像生成超時配置", "file": "vibe-8.html"},
 "739": {"name": "網路失敗代理回退", "file": "vibe-8.html"},
 "740": {"name": "釋出通道走 GitHub", "file": "vibe-9.html"},
 "741": {"name": "方法論寫入原則", "file": "vibe-7.html"},
 "742": {"name": "技術棧與品味規則", "file": "vibe-8.html"},
 "743": {"name": "diff 風險判定", "file": "vibe-9.html"},
 "744": {"name": "違禁模式清單", "file": "vibe-10.html"},
 "745": {"name": "規則落地與維護", "file": "vibe-final.html"},
 "746": {"name": "歷史沿革初始需求", "file": "vibe-7.html"},
 "747": {"name": "響應流式要求", "file": "vibe-8.html"},
 "748": {"name": "風險發現後暫停發版", "file": "vibe-9.html"},
 "749": {"name": "目標以最新為準", "file": "vibe-10.html"},
 "750": {"name": "並行編輯先重讀", "file": "vibe-10.html"}
};
